A = [1 2;3 4];
B = [5 6;7 8];
disp("Matrix A :");
disp(A);
disp("Matrix B :");
disp(B);
addition = A+B;
disp("A+B :");
disp(addition);
subtraction = A-B;
disp("A-B :");
disp(subtraction);
multiplication = A*B;
disp("A*B :");
disp(multiplication);
transpose = A';
disp("Transpose of A :");
disp(transpose);
det_A = det(A);
disp("Determinant of A :");
disp(det_A);
inverse_A = inv(A);
disp("Inverse of A:");
disp(inverse_A);
